-- ============================================================
-- POSngHALAGAko  –  "POS ng Halaga Ko"
-- A Point-of-Sale system for selling emotions & feelings
-- Run this in Supabase SQL Editor
-- ============================================================

-- 1) USERS  (for Login / Sign-Up)
CREATE TABLE IF NOT EXISTS users (
    id          INT GENERATED BY DEFAULT AS IDENTITY,
    username    VARCHAR(50)  NOT NULL,
    password_hash VARCHAR(64) NOT NULL,   -- SHA-256 hex
    full_name   VARCHAR(100) NOT NULL,
    role        VARCHAR(20)  NOT NULL DEFAULT 'cashier',  -- 'admin' or 'cashier'
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username)
);

-- 2) PRODUCTS  (the emotions / feelings for sale)
CREATE TABLE IF NOT EXISTS products (
    id          INT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(255) DEFAULT NULL,
    emoji       VARCHAR(10)  DEFAULT NULL,   -- emoji icon for display
    price       NUMERIC(10,2) NOT NULL,
    stock       INT NOT NULL DEFAULT 999,
    category    VARCHAR(50) NOT NULL DEFAULT 'Emotion',
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

-- 3) TRANSACTIONS  (each completed sale / receipt)
CREATE TABLE IF NOT EXISTS transactions (
    id              INT GENERATED BY DEFAULT AS IDENTITY,
    cashier_id      INT NOT NULL,
    total_amount    NUMERIC(10,2) NOT NULL,
    amount_paid     NUMERIC(10,2) NOT NULL,
    change_amount   NUMERIC(10,2) NOT NULL,
    transaction_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_transactions_cashier FOREIGN KEY (cashier_id) REFERENCES users (id)
);

-- 4) TRANSACTION ITEMS  (line items per sale)
CREATE TABLE IF NOT EXISTS transaction_items (
    id              INT GENERATED BY DEFAULT AS IDENTITY,
    transaction_id  INT NOT NULL,
    product_id      INT NOT NULL,
    product_name    VARCHAR(100) NOT NULL,  -- snapshot at time of sale
    quantity        INT NOT NULL,
    unit_price      NUMERIC(10,2) NOT NULL, -- snapshot at time of sale
    subtotal        NUMERIC(10,2) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_items_transaction FOREIGN KEY (transaction_id) REFERENCES transactions (id),
    CONSTRAINT fk_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

-- ============================================================
-- AUTO-UPDATE trigger for products.updated_at
-- ============================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_products_updated_at ON products;
CREATE TRIGGER trg_products_updated_at
BEFORE UPDATE ON products
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- SEED DATA
-- ============================================================

-- Default admin user  (password: admin123  →  SHA-256)
INSERT INTO users (username, password_hash, full_name, role) VALUES
('admin',   '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'System Admin', 'admin'),
('cashier', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', 'Juan Dela Cruz', 'cashier');

-- Emotions / Feelings catalog
INSERT INTO products (name, description, emoji, price, stock, category) VALUES
('Love',           'A warm, deep affection for someone special',        '❤️',  149.99, 999, 'Core Emotion'),
('Happiness',      'Pure, unfiltered joy and contentment',              '😊',   99.99, 999, 'Core Emotion'),
('Fulfillment',    'The satisfaction of a life well-lived',             '✨',  199.99, 999, 'Core Emotion'),
('Hope',           'The belief that tomorrow will be brighter',         '🌅',   79.99, 999, 'Core Emotion'),
('Peace',          'A calm, serene state of inner tranquility',         '☮️',  129.99, 999, 'Core Emotion'),
('Excitement',     'A thrilling rush of eager anticipation',            '🎉',   89.99, 999, 'Core Emotion'),
('Gratitude',      'A heartfelt thankfulness for what you have',        '🙏',   69.99, 999, 'Core Emotion'),
('Confidence',     'Unshakable self-belief and courage',                '💪',  159.99, 999, 'Premium Emotion'),
('Nostalgia',      'A bittersweet longing for cherished memories',      '📷',  109.99, 999, 'Premium Emotion'),
('Inspiration',    'A spark that ignites creativity and purpose',       '💡',  139.99, 999, 'Premium Emotion'),
('Serenity',       'Deep inner calm beyond ordinary peace',             '🧘',  179.99, 999, 'Premium Emotion'),
('Euphoria',       'An overwhelming wave of pure bliss',                '🌈',  249.99, 999, 'Luxury Emotion'),
('Wonder',         'Childlike amazement at the beauty of existence',    '🤩',  119.99, 999, 'Premium Emotion'),
('Compassion',     'A deep empathy that moves you to help others',      '💕',   99.99, 999, 'Core Emotion'),
('Courage',        'The strength to face fears head-on',                '🦁',  169.99, 999, 'Premium Emotion');
